"""Schémas Pydantic de l'API (instruction/09 §5 : Create / Read / Approval).

Les schémas traduisent les contrats applicatifs (`app/application/dto.py`),
jamais les modèles ORM directement. Les schémas Read exposent les attributs
ORM via ``from_attributes``.
"""

from app.api.schemas.affectation import (
    AffectationProposeeCreate,
    AffectationRead,
    AffectationUpdate,
    CandidatClasse,
    MissionAffectationsRead,
    PropositionAgentRhRead,
)
from app.api.schemas.appel_a_proposition import (
    AppelAPropositionCreate,
    AppelAPropositionRead,
    AppelAPropositionUpdate,
    DecisionCreate,
    ExtractionProposeeCreate,
)
from app.api.schemas.beneficiaire import (
    BeneficiaireCreate,
    BeneficiaireRead,
    BeneficiaireUpdate,
)
from app.api.schemas.document import (
    DocumentCorbeilleRead,
    DocumentDecisionCreate,
    DocumentMetadonneesUpdate,
    DocumentPurgeCreate,
    DocumentRead,
    ExtractionRead,
    ModeleDocumentCreate,
    ModeleDocumentRead,
    RapportPurgeRead,
)
from app.api.schemas.equipe import EquipeCreate, EquipeRead, EquipeUpdate
from app.api.schemas.lieu import LieuCreate, LieuRead, LieuUpdate
from app.api.schemas.lot import LotCreate, LotRead, LotUpdate
from app.api.schemas.mission import (
    MissionDepuisAppelCreate,
    MissionDepuisOffresCreate,
    MissionDirecteCreate,
    MissionLieuUpdate,
    MissionRead,
    MissionStatutUpdate,
    MissionUpdate,
)
from app.api.schemas.offre import (
    BudgetRead,
    BudgetTotalRead,
    LigneBudgetCreate,
    LigneBudgetRead,
    OffreCreate,
    OffreRead,
    OffreResume,
    OffreUpdate,
)
from app.api.schemas.organisation import (
    OrganisationCreate,
    OrganisationRead,
    OrganisationUpdate,
)
from app.api.schemas.session import (
    FichePresenceCreate,
    ImportApercuCreate,
    ImportApercuRead,
    ImportConfirmationCreate,
    ImportLigneCorrigee,
    ImportLigneRead,
    ImportResultatRead,
    ParticipationCreate,
    ParticipationRead,
    ParticipationUpdate,
    PresenceLigne,
    PresenceLotUpdate,
    PresencePointageCreate,
    PresenceRead,
    SessionCreate,
    SessionRead,
    SessionStatutUpdate,
    SessionUpdate,
)
from app.api.schemas.support_formation import (
    SupportFormationCreate,
    SupportFormationRead,
)
from app.api.schemas.suppression import (
    ImpactSuppressionRead,
    RapportSuppressionRead,
    SuppressionRequete,
)

__all__ = [
    "AffectationProposeeCreate",
    "AffectationRead",
    "AffectationUpdate",
    "CandidatClasse",
    "AppelAPropositionCreate",
    "AppelAPropositionRead",
    "AppelAPropositionUpdate",
    "BeneficiaireCreate",
    "BeneficiaireRead",
    "BeneficiaireUpdate",
    "BudgetRead",
    "BudgetTotalRead",
    "DecisionCreate",
    "DocumentCorbeilleRead",
    "DocumentDecisionCreate",
    "DocumentMetadonneesUpdate",
    "DocumentPurgeCreate",
    "DocumentRead",
    "EquipeCreate",
    "EquipeRead",
    "EquipeUpdate",
    "ExtractionProposeeCreate",
    "ExtractionRead",
    "LieuCreate",
    "LieuRead",
    "LieuUpdate",
    "LigneBudgetCreate",
    "LigneBudgetRead",
    "LotCreate",
    "LotRead",
    "LotUpdate",
    "MissionAffectationsRead",
    "PropositionAgentRhRead",
    "MissionDirecteCreate",
    "MissionDepuisAppelCreate",
    "MissionDepuisOffresCreate",
    "MissionRead",
    "MissionUpdate",
    "MissionLieuUpdate",
    "MissionStatutUpdate",
    "ModeleDocumentCreate",
    "ModeleDocumentRead",
    "OffreCreate",
    "OffreRead",
    "OffreResume",
    "OffreUpdate",
    "ImpactSuppressionRead",
    "OrganisationCreate",
    "OrganisationRead",
    "OrganisationUpdate",
    "RapportPurgeRead",
    "FichePresenceCreate",
    "ParticipationCreate",
    "ParticipationRead",
    "ParticipationUpdate",
    "ImportApercuCreate",
    "ImportApercuRead",
    "ImportConfirmationCreate",
    "ImportLigneCorrigee",
    "ImportLigneRead",
    "ImportResultatRead",
    "PresenceLigne",
    "PresenceLotUpdate",
    "PresencePointageCreate",
    "PresenceRead",
    "RapportSuppressionRead",
    "SessionCreate",
    "SessionRead",
    "SessionStatutUpdate",
    "SessionUpdate",
    "SupportFormationCreate",
    "SupportFormationRead",
    "SuppressionRequete",
]
